name: Test listendev

on:
  workflow_dispatch:
  # push:
  # pull_request:
  #   branches:
  #     - main

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - uses: listendev/action@v0.18.0
       with:
         jwt: ${{ secrets.LSTN }}
         runtime: only
         
     - name: Install package
       run: npm install rimraf lodash
       continue-on-error: true
