name: Build combined

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  install-all:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       
     - uses: listendev/action@v0.13.1
       with:
         jwt: ${{ secrets.LSTN }}
         runtime: only

     - name: Install and simulate runtime
       run: |
          # Install and run test app
          cd test-app
          npm install
          npm test
       continue-on-error: true
