name: Build app

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  install-all:
    runs-on: ubuntu-latest

    steps:



         
     - name: Checkout repository
       uses: actions/checkout@v2
     - uses: listendev/action@v0.10
       with:
         jwt: ${{ secrets.LS }}
         ci: only
  
  
     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
         node-version: 18

     - name: Install dependencies
       run: npm install .
