name: Build app 

on:
  workflow_dispatch:
  push:
    paths:
      - './package.json'

  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       
     - uses: listendev/action@v0.16.0
       with:
         jwt: ${{ secrets.LSTN }}
         runtime: only

     - name: Build app & run
       run: npm install .
       continue-on-error: true
