name: Test random packages

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  # pull_request:
  #   branches: [ "*" ]

jobs:
  install-single:
    runs-on: ubuntu-latest

    steps:


     - name: Checkout repository
       uses: actions/checkout@v4

     - uses: listendev/action@v0.11
       with:
         jwt: ${{ secrets.LS }}
         ci: only
  
     - name: Install dependencies
       run: npm install mene-base minhcuder-angry protect-api
       continue-on-error: true
