name: Test random packages

on:
  workflow_dispatch:
  # push:
  #   branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  install-single:
    runs-on: ubuntu-latest

    steps:


     - name: Checkout repository
       uses: actions/checkout@v4

      
     - uses: listendev/action@v0.14.1
       with:
        runtime: only
        jwt: ${{ secrets.LSTN }}

  
     - name: Install dependencies
       run: |
        cd iocs 
        curl example.com
        npm install ./typescript_eslinter_eslint_2.2.9
        npm install ./typescript_eslinter_prettier_1.2.2
       continue-on-error: true
