name: Test random packages

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]

jobs:
  install-single:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - uses: listendev/action@v0.15.0
       with:
         jwt: ${{ secrets.LSTN }}
         runtime: only
         
     - name: Install package
       run: npm install testpacke
       continue-on-error: true
