name: Test random packages

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]

jobs:
  install-single:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - uses: listendev/action@v0.14.1
       with:
         jwt: ${{ secrets.LSTN }}
         runtime: only
     - name: Install from npmjs
       run: npm install @async-mutex/mutex dexscreener
       continue-on-error: true
       

     # - name: Install package from local
     #   run: |
     #    cd iocs && npm install ./0xengine_xmlrpc_1.3.4
     #   continue-on-error: true
