name: Test from registry

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/install-single.yml'
  pull_request:


jobs:
  install-single:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - uses: listendev/action@v0.16.0
       with:
         jwt: ${{ secrets.LSTN }}
         runtime: only
         
     - name: Install package
       run: npm install rimraf whatsapp-sdk-docs
       continue-on-error: true
