name: Test self hosted runner
on:
  workflow_dispatch:


jobs:
  install-single:
    runs-on: depot-ubuntu-22.04

    steps:


     - name: Checkout repository
       uses: actions/checkout@v4

     - uses: listendev/action@v0.12
       with:
         jwt: ${{ secrets.LS }}
         ci: only

     - name: Install dependencies
       run: npm install llm-oracle
       continue-on-error: true