name: Test iocs

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  install-iocs:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       
     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '18'

     - uses: listendev/action@v0.12
       with:
         jwt: ${{ secrets.LSTN }}
         ci: only
         
     - name: Install test dependencies
       run: |
         npm install puppeteer
         npm install @peculiar/webcrypto
         npm install node-fetch@2
         npm install @solana/web3.js@1.94.0  # Known good version for baseline

     - name: Install IOC dependencies 1
       run: npm install ./iocs/solana_web3.js_1.95.6
       continue-on-error: true

     - name: Install IOC dependencies 2
       run: npm install ./iocs/solana_web3.js_1.95.7
       continue-on-error: true

     - name: Run Comparison Tests
       run: node ./iocs/tests/solana-web3.test.js
       continue-on-error: true

     - name: Generate Report
       if: always()
       run: |
         echo "### Test Results" >> $GITHUB_STEP_SUMMARY
         cat test-output.log >> $GITHUB_STEP_SUMMARY
         
         if grep -q "SECURITY WARNINGS" test-output.log; then
           echo "::warning::Potential malicious behavior detected"
           echo "::error::Security anomalies found in tested versions"
           exit 1
         fi
