name: Test v0.13

on:
  workflow_dispatch:
  # push:
  #   branches: [ "*" ]
  # pull_request:
  #   branches: [ "*" ]

jobs:
  test-release:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: listendev/action@v0.13.1
      with:
        jwt: ${{ secrets.LS2 }}
        runtime: only

    - name: Install dependencies
      run: npm install .
