name: Test iocs

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test-1-95-6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install puppeteer @peculiar/webcrypto node-fetch@2
          npm install ./iocs/solana_web3.js_1.95.6
      - name: Run Tests
        run: node ./iocs/tests/runners/test-1.95.6.js
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-1.95.6
          path: test-results-1.95.6.json

  test-1-95-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install puppeteer @peculiar/webcrypto node-fetch@2
          npm install ./iocs/solana_web3.js_1.95.7
      - name: Run Tests
        run: node ./iocs/tests/runners/test-1.95.7.js
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-1.95.7
          path: test-results-1.95.7.json

  test-safe-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install puppeteer @peculiar/webcrypto node-fetch@2
          npm install @solana/web3.js@1.94.0
      - name: Run Tests
        run: node ./iocs/tests/runners/test-safe.js
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-safe
          path: test-results-safe.json

  analyze-results:
    needs: [test-1-95-6, test-1-95-7, test-safe-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Generate comparison report
        run: |
          echo "### Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "#### Wallet Operations" >> $GITHUB_STEP_SUMMARY
          echo "| Version | Success | Suspicious Patterns |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|---------|-------------------|" >> $GITHUB_STEP_SUMMARY
          for version in "1.95.6" "1.95.7" "safe"; do
            result=$(cat test-results-$version/test-results-$version.json)
            success=$(echo $result | jq -r '.walletOperations.success')
            patterns=$(echo $result | jq -r '.walletOperations.patterns | length')
            echo "| $version | $success | $patterns |" >> $GITHUB_STEP_SUMMARY
          done
