name: Test v0.0

on:
  workflow_dispatch:
  # push:
  #   branches: [ "*" ]
  # pull_request:
  #   branches: [ "*" ]

jobs:
  test-release:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: listendev/action@v0.11   
      with:
        jwt: ${{ secrets.LS }}
        ci: only
        argus_version: v0.0


    - name: Install dependencies
      run: npm install .
