name: Test IOCs

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test-1-95-6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install test dependencies
        run: |
          npm install puppeteer @peculiar/webcrypto node-fetch@2

      - uses: listendev/action@v0.12
        with:
          jwt: ${{ secrets.LSTN }}
          ci: only
      - name: Install IOC 1.95.6
        run: npm install ./iocs/solana_web3.js_1.95.6
      - name: Test Version 1.95.6
        run: node ./iocs/tests/runners/test-1.95.6.js
        continue-on-error: true

  test-1-95-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install test dependencies
        run: |
          npm install puppeteer @peculiar/webcrypto node-fetch@2
      - uses: listendev/action@v0.12
        with:
          jwt: ${{ secrets.LSTN }}
          ci: only
      - name: Install IOC 1.95.7
        run: npm install ./iocs/solana_web3.js_1.95.7
      - name: Test Version 1.95.7
        run: node ./iocs/tests/runners/test-1.95.7.js
        continue-on-error: true

  test-safe-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install test dependencies
        run: |
          npm install puppeteer @peculiar/webcrypto node-fetch@2
      - uses: listendev/action@v0.12
        with:
          jwt: ${{ secrets.LSTN }}
          ci: only
      - name: Install safe version
        run: npm install @solana/web3.js@1.95.8
      - name: Test Safe Version
        run: node ./iocs/tests/runners/test-safe.js
        continue-on-error: true


