name: Test local modules
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-local.yml'
      - './iocs'

jobs:
  test-local-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        

     - uses: listendev/action@v0.15.0
       with:
         jwt: ${{ secrets.LSTN }}
         runtime: only
         
      - name: Install local modules
        run: |
          for module in ./iocs/*.tgz; do
            npm install "$module"
          done
        continue-on-error: true