name: Test local modules
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-local.yml'
  pull_request:
    paths:
      - 'iocs/**' 
      - '.github/workflows/test-local.yml'

  
jobs:
  test-local-npm-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Run Garnet Security Scanner
        uses: garnet-org/action@v1
        with:
          api_token: ${{ secrets.GARNET_KEY }}
          debug: true


      - name: Install local modules
        run: |
          if [ ! -d "iocs" ]; then
            echo "::error::Missing IOCs directory"
            exit 1
          fi
          cd iocs
          shopt -s nullglob
          for module in *.tgz; do
            echo "Installing $module..."
            npm install --no-audit --loglevel=error "$module" || true
          done
          shopt -u nullglob
        continue-on-error: true

      - name: Verify installations
        run: |
          npm ls --all --depth=0 || true
          echo "Installed packages:"
          ls -la node_modules/ || true
